# fly.toml app configuration file generated for telegram-vision-bot on 2025-11-12T20:24:49+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'telegram-vision-bot'
primary_region = 'cdg'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
 source = "bot_data"
 destination = "/data"
